### PR TITLE
add macOS TTS via the command line “say”

### PR DESCRIPTION
**Pull request by chrisvaughn**
* currently all voices listed/supported are the default voices included with macOS 10.12
* higher quality versions of those voices can be downloaded from the macOS Systems panel, not sure the best place to document this.

### CODE REVIEW

**Comment by chrisvaughn** [comment]
@readbeyond here is my adaptation of my custom TTS wrapper into a supported TTS wrapper. I've ran all unit tests using the 'run_all_unit_tests.py' script. Please feel free to give input & feedback for revision or take the branch over to finish the work if more comprehensive work needs to be done.

**Comment by readbeyond** [comment]
@chrisvaughn  Excellent, thank you. it LGTM, I am merging it.

Two questions:

1. Do you need a new release of aeneas in a short time frame? I was thinking of addressing #130 before releasing as v1.8.0, but if you need/prefer an intermediate v1.7.2 shipping the MacOS wrapper, I can do it, without the work on #130.
2. I am going to credit your contribution in the Acknowledgment section of the README. Is it fine with you? Is "Chris Vaughn" correct or you prefer another string?

Thanks you again for your contribution!

**Comment by chrisvaughn** [comment]
@readbeyond Thanks for the merge.  I'm happy to contribute!

1. I think I can do a local install of the devel branch for my use case for now. I'm ok with waiting for the next planned release. 
2. Yes. "Chris Vaughn" is correct.  Thanks for adding me to the Acknowledgement section.

**Comment by readbeyond** [comment]
Hi @chrisvaughn , thank you for the quick reply.

I have just pushed to `devel` a couple of minor enhancements: (  	e99110e , 675d1b1 , and d35b091 ) and added a mention of the MacOS TTS in the relevant places of the documentation, and the ack in the README.

(Plus, the current `devel` also updates 2016 to 2017 in the copyright comments/messages.)

Alright, in a couple of weeks I should either take care of #130 or just promote the current `devel` to `master` (and push to PyPI, etc.).

**Pull request merged**
