### PR TITLE
Fix various memory leaks in C extension modules

### PR DESCRIPTION
**Pull request by rotemdan**
Possibly partial fix for #205. This may not cover everything but seems to help so far.

### CODE REVIEW

**Comment by readbeyond** [comment]
@rotemdan Would you mind changing the branch to devel instead of master, please?

See: https://github.com/readbeyond/aeneas/blob/master/wiki/CONTRIBUTING.md#branch-policy

**Comment by rotemdan** [comment]
@readbeyond I changed the branch to devel.

BTW `aeneas.cdtw.cdtw.compute_best_path` seems to be leaking memory as well:

```py
import numpy as np
import cmfcc
import aeneas.cdtw.cdtw
import gc
import time

audioFloats = np.frombuffer(bytes(int(10000000)), dtype='int16').astype('float64') / 32768
audioMFCCs1, _, _ = cmfcc.compute_from_data(audioFloats, 16000, 40, 13, 512, 133.3333, 6855.4976, 0.97, 0.025, 0.010)
audioMFCCs2, _, _ = cmfcc.compute_from_data(audioFloats, 16000, 40, 13, 512, 133.3333, 6855.4976, 0.97, 0.025, 0.010)

transposedMFCCs1 = np.transpose(audioMFCCs1)
transposedMFCCs2 = np.transpose(audioMFCCs2)

for i in range (0, 1000):
	print(i)
	dtw = aeneas.cdtw.cdtw.compute_best_path(transposedMFCCs1, transposedMFCCs2, 100)
	del dtw
	gc.collect()
	time.sleep(0.1)

```
I don't believe it's the return value here since it is a python list. I've tried to add the flag to internal `ndarrays` created with `PyArray_SimpleNew` but so far no luck. Could also be a reference count issue.

**Comment by rotemdan** [comment]
Update:

Turns out the leaks in `compute_best_path` are probably not related to numpy objects (I tried to methodically exit the function at several points to verify this)

However, the the tuples elements within the returned path object seem to have a refcount of 3 instead of the expected 2 (sys.getrefcount() adds 1 to result).

Decreasing the refcount on each tuple after it is added to the list:
```c
static void _append(PyObject *list, uint32_t i, uint32_t j) {
    PyObject *tuple;

    tuple = PyTuple_New(2);
    // PyTuple_SetItem steals a reference, so no PyDECREF is needed
    PyTuple_SetItem(tuple, 0, Py_BuildValue("I", i));
    PyTuple_SetItem(tuple, 1, Py_BuildValue("I", j));
    PyList_Append(list, tuple);
    
    Py_DECREF(tuple); // <--
}
```
seems to help. But there's still a small amount of memory leaked.

**Comment by rotemdan** [comment]
I added a new commit with the `Py_DECREF` call. After a secondary, longer test it seems like there is no leak anymore in `compute_best_path` (there was a slight increase in memory in the first few rounds but it seemed to have stabilized). There's still much to be explored though.

**Comment by readbeyond** [comment]
Hi, I have not had time to dig into all the details, but I tested and reviewed your patch, and it looks good, so I am merging.

I am adding to the acknowledgment section in a subsequent commit.

**Pull request merged**
