### PR TITLE
Changes to allow easier compilation on Windows platforms

### PR DESCRIPTION
**Pull request by eomerdws**
The changes will allow compilation on both Win 32 and Win 64. The main changes were inspired by this Python issue & particular comment:
* https://bugs.python.org/issue23246
* https://bugs.python.org/msg234140

Other minor changes:
* Deletion of the "compile_c_extensions" batch and sh files as they are no longer needed under any platform. Now simply using 'python setup.py build' will build the extensions. This was tested under Windows 7 (Python 2.7 32-bit), Windows 7 (Python 2.7 64-bit), and Ubuntu 14.04 stock Python 2.7.
* Also changed documentation to reflect change in c compilation.
* Adjusted .gitignore (since I use PyDev, and on Windows the extensions compile to .pyd files)
* Changed the cdtw_setup.py and cmfcc_setup.py files to print deprecated messages with short instructions to build.

### CODE REVIEW

**Comment by pettarin** [comment]
Dear David, thank you for this! I planned to study the setup options, but I am glad you preceded me.

Your push looks good to me and I will merge it, but I have two --- hopefully simple to implement --- requests, to help me merging your push:

1. if you can use the Python 2.x, `print` instead of `print_function` from `future` (just for consistency with the rest of the code)

2. if you can squash together your commits (see https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit)

Thank you!

**Comment by eomerdws** [comment]
Sure. It's done!

**Comment by pettarin** [comment]
Great, thank you.

I cloned your repo on my Debian machine, and `$ python setup.py build` (run as regular user on the shell) builds the two `.so` files in the `$AENEAS_ROOT/build/`directory, but it does not copy them into the `$AENEAS_ROOT/aeneas/` directory. As a consequence, trying to run e.g. `execute_task` will lead to the "no C extensions" warning.

Instead, if I run `$ python setup.py build_ext --inplace`, the `.so` files are copied into the `$AENEAS_ROOT/aeneas/` directory, and they work as expected.

I think that, at this stage, the latter behavior is more desirable for the end user, who does not have to manually locate and copy the `.so` files.

Is it the same on Ubuntu or Windows? Did you run the `setup.py` as root? Am I missing something?

(Apologies for being picky, I am a `distutils`/`setuptools` rookie.)

**Comment by eomerdws** [comment]
So I probably should have included this in the documentation. For normal users after the build you can type ```python setup.py install```. Normally this is as root or with sudo rights. It then installs the Python code and extensions into the site-packages for that version of Python. Then the command line should work anywhere where the Python command would work (I say should because if someone builds it in a virtual env or perhaps on some other localized version of Python this would be different).

My recommendation (just a recommendation) would be to check and see if `the ``__status__``` in setup.py is equal to something like 'Dev' or 'Debug' and then have it run the --inplace command as well. That way you have the best of both worlds and only a single command. Again this is just a recommendation. If you'd prefer it the other way I'll gladly add it back.

Thanks for your awesome project! Oh and I should mention I'm a newbie at distutils and setuptools. I have used them once before, but a lot has changed since then. So by far I am no expert. Just thought since you were asking for assistance in this area it was a great excuse to learn again!

**Comment by pettarin** [comment]
Thank you for the explanation. I have a much clearer picture now.

I did a quick test (Debian, unprivileged user):

```
$ git clone https://github.com/eomerdws/aeneas
$ python setup.py build
$ python setup.py install
```

and the last failed (it attempts to write /usr/local/... so it expects to be run as root).

I like the idea of not having bash/bat scripts, so I would like to keep your `setup.py`. However, to avoid creating too many potential support issues, I would prefer going with `python setup.py build_ext --inplace` at the moment. Maybe adding a note like "if you want to install aeneas system-wise, use `$ sudo python setup.py install`".

The long term solution will consists in me uploading aeneas in the PyPI. I just want to finish working on v1.2.0, which should be done next week, so that I can start working on the PyPI upload.

Now: if you have time to edit your push, according to what I wrote above, please go ahead and I will just merge it. Otherwise, I will merge your push as it is now, edit it, and squash the last two commits together. The resulting thing will be "v1.1.2".

Thank you again for your time.

**Comment by readbeyond** [comment]
Alright, I am going to merge your push now, and modify it as described above.

**Comment by readbeyond** [comment]
Updated. Thank you! I acknowledge you in the changelog, plus your push is recorded in the GitHub repo stats.

Closing this pull request.

**Comment by eomerdws** [comment]
Awesome thanks! Sorry I did not have a chance to work on it today.

**Comment by readbeyond** [comment]
On 09/24/2015 12:00 PM, David Smith wrote:
> Awesome thanks! Sorry I did not have a chance to work on it today.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/readbeyond/aeneas/pull/7#issuecomment-142878987>.
>

Do not worry. I took the chance to add the changelog message and other 
minor things.

Thank you again!

**Pull request merged**
