### PR TITLE
Only espeak.lib is necessary to compile aeneas.cew. Yet espeak.dll is necessary at runtime...

### PR DESCRIPTION
**Pull request by danielbair**
Only espeak.lib is necessary to compile aeneas.cew, and if it doesn't exist then the compile will fail.

Yet even though espeak.dll is needed at runtime by aeneas.cew, if it doesn't exist aeneas will still function, but it will assume that aeneas.cew wasn't compiled.

### CODE REVIEW

**Comment by pettarin** [comment]
Hi Daniel,

thanks for making this more precise.

Do you need this patch to be on the ``master`` branch immediately? If not, I prefer merging it on the ``devel`` branch, keeping the code on the ``master`` in sync with the latest version available on PyPI, and releasing the change on the next version, thank you.

**Comment by pettarin** [comment]
Another quick question. With this comment:

https://github.com/danielbair/aeneas/blob/e31de53f38088b55617a3d3e7dcea2cde4b467d3/setup.py#L78

are you suggesting that putting the ``espeak.dll`` in the ``aeneas/cew`` subdirectory (instead of ``System32``) works? Because I seem to remember that I tried that one once, and it did not work for me, albeit I should check again, it might have been an issue with something else.

I am asking because, if true, it might be worth considering copying the DLL there, instead of ``System32``, to avoid permission issues, since ``aeneas/cew`` can be written by the process performing the setup, while ``System32`` might not. What do you think?

**Comment by danielbair** [comment]
Actually copying espeak.dll to the aeneas\cew directory was working in my tests, but you would need to edit the setup function to package the dll when installing to python site-packages on windows builds. (I do believe that this would be best as it does avoid permissions issues.)
`    package_data={
        "aeneas": ["res/*", "*.md"],
        "aeneas.cdtw": ["*.c", "*.h", "*.md"],
        "aeneas.cew": ["*.c", "*.h", "*.md", "*.dll"],
        ...`

I also fould that espeak.lib could be copied to the root folder of aeneas, where setup.py is located.

And, checking for espeak.dll in C:\Windows\System32 doesn't work on 64bit Windows as the copy operation of espeak.dll to C:\Windows\System32 is redirected to C:\Winsows\SysWOW64 by the OS.

No, this patch is not needed immediately. I have this patch being applied to the aeneas-installer build for Windows automatically on my end. I was just sharing it with you for your info.

**Comment by danielbair** [comment]
BTW, If aeneas.cew was compiled on one machine and copied to another via a python wheel or such, and espeak.dll or libespeak.dylib don't exist on the second machine, aeneas.diagnostics will report that "aeneas.cew wasn't complied" even though it was, and if later the dll or dylib are available it will then report that "aeneas.cew was compiled". If you really want to know if aeneas.cew was compiled I believe you would have to check if the cew.so or cew.pyd files exist. If those files do exist then you could notify the user that aeneas.cew can't find the espeak library.

**Comment by pettarin** [comment]
Hi Daniel,

thanks a lot for taking time to investigate all this. I am positive doing this:

1. copying espeak.dll in the aeneas/cew directory,
2. copying espeak.lib in the root directory containing setup.py,

changing the setup.py accordingly, as it seems the best way to avoid the 32/64 bit Windows path ambiguity, and the permission issue.

With respect to the messages, until now I fused the "compiled" with the "available at runtime" concept for cew. I will review the message strings about that.

Since the diagnostics are meant to be run after the package setup has completed, I think it should check only the "available at runtime" thing, by attempting to load the corresponding Python module, as it does for cmfcc and cdtw, saying "AVAILABLE" instead of "COMPILED". Does it make sense to you?

If I can help you avoid patching, I am ok merging these changes, releasing as v1.5.1.1. Otherwise, just open another PR on the ``devel`` branch, and it will be released next time.

**Comment by danielbair** [comment]
I have moved this to https://github.com/danielbair/aeneas/pull/1 now.

**Comment by danielbair** [comment]
BTW, I have not been able to get espeak/espeak.dll to compile on 64-bit Windows, so for anyone on MS Windows they will have to use 32-bit Python/eSpeak/FFmpeg to have aeneas.cew functioning. (And cew on 32-bit Windows is much faster than NO cew on 64-bit Windows.)

**Comment by danielbair** [comment]
FYI, I have been able to test aeneas on Mac OS X 10.6 and up. Getting homebrew on 10.6 was a challenge though. Installing homebrew and aeneas on 10.7 and up was fairly simple. I haven't tested on python3.x yet, only python2.7 for now.

**Comment by readbeyond** [comment]
Got it, thank you for the information.

**Pull request closed without merging**
